package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/services"
)

// UpdateGoEnterpriseOffsets is the resolver for the updateGoEnterpriseOffsets field.
func (r *mutationResolver) UpdateGoEnterpriseOffsets(ctx context.Context, content string) (bool, error) {
	if err := services.UpdateGoEnterpriseOffsets(ctx, content); err != nil {
		return false, err
	}
	return true, nil
}

// CheckGoEnterpriseOffsetsUpdates is the resolver for the checkGoEnterpriseOffsetsUpdates field.
func (r *mutationResolver) CheckGoEnterpriseOffsetsUpdates(ctx context.Context, content string) (*model.GoEnterpriseOffsetsUpdateCheck, error) {
	return services.CheckGoEnterpriseOffsetsUpdates(ctx, content)
}

// GoEnterpriseOffsets is the resolver for the goEnterpriseOffsets field.
func (r *queryResolver) GoEnterpriseOffsets(ctx context.Context) (*model.GoEnterpriseOffsets, error) {
	return services.GetGoEnterpriseOffsets(ctx)
}
