package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/odigos-io/odigos/frontend/graph/model"
	"github.com/odigos-io/odigos/frontend/services"
)

// UnmatchedURLPaths is the resolver for the unmatchedUrlPaths field.
func (r *queryResolver) UnmatchedURLPaths(ctx context.Context, namespace string, kind string, name string) (*model.UnmatchedURLPaths, error) {
	return services.GetUnmatchedUrlPaths(ctx, namespace, kind, name)
}
