// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("odigosservicename")
	ScopeName = "github.com/odigos-io/odigos/collector/processor/odigosservicenameprocessor"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
