package logs

import (
	"context"
	"slices"

	actionv1 "github.com/odigos-io/odigos/api/actions/v1alpha1"
	odigosv1 "github.com/odigos-io/odigos/api/odigos/v1alpha1"
	"github.com/odigos-io/odigos/common"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

const (
	K8sAttributesActionName = "autogenerated-logs-k8sattributes"
)

type CollectorsGroupReconciler struct {
	client.Client
}

func (r *CollectorsGroupReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {

	var clusterCg = &odigosv1.CollectorsGroup{}
	err := r.Get(ctx, req.NamespacedName, clusterCg)
	if err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	logsEnabledInOdigos := slices.Contains(clusterCg.Status.ReceiverSignals, common.LogsObservabilitySignal)

	if logsEnabledInOdigos {

		k8sAttributesAction := &actionv1.K8sAttributesResolver{
			TypeMeta: metav1.TypeMeta{
				Kind:       "K8sAttributesResolver",
				APIVersion: "actions.odigos.io",
			},
			ObjectMeta: metav1.ObjectMeta{
				Name:      K8sAttributesActionName,
				Namespace: req.Namespace,
				OwnerReferences: []metav1.OwnerReference{
					{
						APIVersion: "odigos.io/v1alpha1",
						Kind:       "CollectorsGroup",
						Name:       clusterCg.Name,
						UID:        clusterCg.UID,
					},
				},
			},
			Spec: actionv1.K8sAttributesSpec{
				ActionName: "auto-generated action to enhance logs with workload names",
				Disabled:   false,
				Notes: "This action will add `k8s.deployment.name`, `k8s.statefulset.name` or `k8s.daemonset.name` to logs collected by odigos." +
					" This action is automatically generated and controlled by odigos.",
				Signals: []common.ObservabilitySignal{common.LogsObservabilitySignal},
			},
		}

		err := r.Patch(ctx, k8sAttributesAction, client.Apply, client.ForceOwnership, client.FieldOwner("autoscaler-logs"))
		if err != nil {
			return ctrl.Result{}, err
		}
	}

	return ctrl.Result{}, nil
}
