on:
  push:
    branches:
    - main
  
permissions:
  contents: write
  pull-requests: write
  
name: Create Odigos Release PR
  
jobs:
  calculate-new-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    
  